# Generated by Django 5.1.2 on 2024-11-06 08:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogapp', '0006_react'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='react',
            unique_together={('blog', 'user')},
        ),
    ]
