# Generated by Django 5.1.2 on 2024-11-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogapp', '0007_alter_react_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('react', 'react'), ('comment', 'comment'), ('status', 'status')], max_length=20),
        ),
    ]
